// Core domain types. Instruments/transactions/sips/watchlist are persisted (Dexie);
// Holding/PortfolioSummary are computed on the fly.

export type InstrumentType = 'stock' | 'mf'

export interface Instrument {
  id: string // "stock:RELIANCE.NS" | "mf:118550"
  type: InstrumentType
  name: string
  symbol?: string // stocks, e.g. "RELIANCE.NS"
  schemeCode?: number // mutual funds
  exchange?: string // "NSE" | "BSE"
  category?: string // MF category / stock sector
  currency: string // "INR"
  createdAt: number
}

export type TxnKind = 'buy' | 'sell'

export interface Transaction {
  id: string
  instrumentId: string
  kind: TxnKind
  date: string // ISO yyyy-mm-dd
  units: number
  price: number // per unit (NAV for MF)
  fees: number
  notes?: string
  sipId?: string // set when auto-generated by a SIP
  createdAt: number
}

export type SipFrequency = 'weekly' | 'fortnightly' | 'monthly'

export interface Sip {
  id: string
  instrumentId: string
  amount: number // INR per installment
  frequency: SipFrequency
  startDate: string // ISO
  active: boolean
  lastRun?: string // ISO date of the last materialized installment
  createdAt: number
}

export interface WatchItem {
  id: string // = instrumentId
  instrumentId: string
  addedAt: number
}

export interface PriceSnapshot {
  instrumentId: string
  price: number
  prevClose: number
  asOf: number // epoch ms
  name?: string
  currency?: string
}

export interface Setting {
  key: string
  value: unknown
}

// ---- Computed ----

export interface Holding {
  instrument: Instrument
  units: number // net held units
  investedValue: number // cost basis of currently-held units
  avgCost: number
  price: number // latest price/NAV
  prevClose: number
  currentValue: number
  pnl: number // unrealized
  pnlPct: number
  dayChange: number // units * (price - prevClose)
  dayChangePct: number
  realizedPnl: number
  priceAsOf?: number
  hasPrice: boolean
}

export interface PortfolioSummary {
  invested: number
  currentValue: number
  totalPnl: number
  totalPnlPct: number
  dayChange: number
  dayChangePct: number
  realizedPnl: number
  xirr: number | null // percent, e.g. 14.2
  holdings: Holding[] // held positions (units > 0), sorted by value desc
  byType: { stock: number; mf: number }
}
